WebLayout/WebLayout/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebLayout.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebLayout/WebLayout/Controllers/ParametrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebLayout.Controllers
{
    public class ParametrosController : Controller
    {
        // GET: Parametros
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebLayout/WebLayout/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

   
<div class="content-header row">
    <div class="content-header-left col-md-8 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">Advance Statistics Cards</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">Components</a>
                    </li>
                    <li class="breadcrumb-item active">
                        Statistics Cards
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <div class="content-header-right col-md-4 col-12">
        <div class="btn-group float-md-right">
            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="icon-settings mr-1"></i>Action</button>
            <div class="dropdown-menu arrow">
                <a class="dropdown-item" href="#"><i class="fa fa-calendar mr-1"></i> Calender</a><a class="dropdown-item" href="#"><i class="fa fa-cart-plus mr-1"></i> Cart</a><a class="dropdown-item" href="#"><i class="fa fa-life-ring mr-1"></i> Support</a>
                <div class="dropdown-divider"></div><a class="dropdown-item" href="#"><i class="fa fa-cog mr-1"></i> Settings</a>
            </div>
        </div>
    </div>
</div>

<div class="content-body">
    <!-- Minimal statistics section start -->
    <section id="minimal-crypto-statistics-bg">
        <div class="content-header row">
            <div class="col-12 mt-3 mb-1">
                <h4 class="text-uppercase">Crypto Wallet Statistics With Background Color</h4>
                <p>Statistics on minimal cards with background color.</p>
            </div>
        </div>

        <!-- Crypto Stats 1 -->
        <div id="crypto-stats-3" class="row">
            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card crypto-card-3 bg-info">
                    <div class="card-content">
                        <div class="card-body cc XRP pb-1">
                            <h4 class="text-white mb-3"><i class="cc XRP" title="XRP"></i> Ripple</h4>
                            <h6 class="text-white mb-1">Balance</h6>
                            <h4 class="text-white">200 XRP</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card crypto-card-3 bg-warning">
                    <div class="card-content">
                        <div class="card-body cc BTC pb-1">
                            <h4 class="text-white mb-3"><i class="cc BTC" title="BTC"></i> Bitcoin</h4>
                            <h6 class="text-white mb-1">Balance</h6>
                            <h4 class="text-white">3.5 BTC</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card crypto-card-3 bg-danger">
                    <div class="card-content">
                        <div class="card-body cc ETH pb-1">
                            <h4 class="text-white mb-3"><i class="cc ETH" title="ETH"></i> Ethereum</h4>
                            <h6 class="text-white mb-1">Balance</h6>
                            <h4 class="text-white">10 ETH</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-12">
                <div class="card crypto-card-3 bg-success">
                    <div class="card-content">
                        <div class="card-body cc LTC pb-1">
                            <h4 class="text-white mb-3"><i class="cc LTC" title="LTC"></i> Litecoin</h4>
                            <h6 class="text-white mb-1">Balance</h6>
                            <h6 class="text-white">24 LTC</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

WebLayout/WebLayout/Views/Parametros/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="sidebar-detached sidebar-left">
    <div class="sidebar">
        <div class="bug-list-sidebar-content">
            <!-- Predefined Views -->
            <div class="card">
                <!-- contacts view -->
                <div class="card-body">
                    <div class="list-group">
                        <a href="#" class="list-group-item active">Produto</a>
                        <a href="#" class="list-group-item list-group-item-action">Recently contacted <span class="badge badge-primary badge-pill float-right">14</span></a>
                        <a href="#" class="list-group-item list-group-item-action">Favorite contacts <span class="badge badge-primary badge-pill float-right">14</span></a>
                    </div>
                    <div class="list-group">
                        <a href="#" class="list-group-item active">All Contacts</a>
                        <a href="#" class="list-group-item list-group-item-action">Recently contacted</a>
                        <a href="#" class="list-group-item list-group-item-action">Favorite contacts</a>
                    </div>
                </div>
            </div>
            <!--/ Predefined Views -->

        </div>
    </div>
</div>

<section class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Ladda Buttons with Icons</h4>
                <div class="heading-elements">
                    <button class="btn btn-primary"><i class="ft-plus white"></i> Inserir</button>
                </div>
            </div>
            <div class="card-body collapse show">
                <div class="card-block">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="form-group">
                                <table id="users-contacts" class="table table-white-space table-bordered row-grouping display no-wrap icheck table-middle dataTable" role="grid" aria-describedby="users-contacts_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting" tabindex="0" aria-controls="users-contacts" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 186px;">Name</th>
                                            <th class="sorting" tabindex="0" aria-controls="users-contacts" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending" style="width: 198px;">Email</th>
                                            <th class="sorting" tabindex="0" aria-controls="users-contacts" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending" style="width: 114px;">Phone</th>
                                            <th class="sorting" tabindex="0" aria-controls="users-contacts" rowspan="1" colspan="1" aria-label="Favorite: activate to sort column ascending" style="width: 78px;">Favorite</th>
                                            <th class="sorting" tabindex="0" aria-controls="users-contacts" rowspan="1" colspan="1" aria-label="Actions: activate to sort column ascending" style="width: 83px;">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr role="row" class="odd">
                                            <td>
                                                <div class="media">
                                                    <div class="media-left pr-1">
                                                        <span class="avatar avatar-sm avatar-online rounded-circle"><img src="../../../app-assets/images/portrait/small/avatar-s-2.png" alt="avatar"><i></i></span>
                                                    </div>
                                                    <div class="media-body media-middle">
                                                        <a href="#" class="media-heading">Alice Collins</a>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="text-center">
                                                <a href="mailto:email@example.com">alice@example.com</a>
                                            </td>
                                            <td>+658-254-256</td>
                                            <td class="text-center"><i class="fa fa-star  yellow darken-2"></i></td>
                                            <td>
                                                <button class="btn btn-info btn-sm" data-style="zoom-out">
                                                    <span class="ladda-label"><i class="fas fa-edit"></i></span>
                                                </button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-xl-12">
                            <div class="form-group">
                                <!-- Zoom Buttons with icons -->
                                <button class="btn btn-info btn-min-width mr-1 mb-1 ladda-button" data-style="zoom-in"><span class="ladda-label"><i class="ft-plus"></i> Zoom in</span></button>

                                <button class="btn btn-info btn-min-width mr-1 mb-1 ladda-button" data-style="zoom-out"><span class="ladda-label"><i class="ft-minus"></i> Zoom out</span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebLayout/WebLayout/Views/Shared/_Layout.cshtml
<html class="loaded" lang="en" data-textdirection="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Robust admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template.">
    <meta name="keywords" content="admin template, robust admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
    <meta name="author" content="PIXINVENT">
    <title>Dashboard eCommerce - Robust - Responsive Bootstrap 4 Admin Dashboard Template for Web Application</title>
    <link rel="apple-touch-icon" href="https://pixinvent.com/bootstrap-admin-template/robust/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="https://pixinvent.com/bootstrap-admin-template/robust/app-assets/images/ico/favicon.ico">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/icons")

</head>

<body class="vertical-layout 2-columns fixed-navbar pace-done menu-expanded vertical-menu" data-open="click" data-menu="vertical-menu" data-col="2-columns">
    <div class="pace  pace-inactive">
        <div class="pace-progress" data-progress-text="100%" data-progress="99" style="transform: translate3d(100%, 0px, 0px);">
            <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
    </div>

    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-semi-dark navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav flex-row">
                    <li class="nav-item mobile-menu d-md-none mr-auto">
                        <a class="nav-link nav-menu-main menu-toggle hidden-xs is-active" href="#">
                            <i class="ft-menu font-large-1"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="../../../html/ltr/vertical-menu-template/index.html">
                            <img class="brand-logo" alt="robust admin logo" src="~/Content/img/nave_icon.png">
                            <h3 class="brand-text">Robust Admin</h3>
                        </a>
                    </li>
                    <li class="nav-item d-md-none"><a class="nav-link open-navbar-container collapsed" data-toggle="collapse" data-target="#navbar-mobile" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a></li>
                </ul>
            </div>
            <div class="navbar-container content">
                <div class="navbar-collapse collapse" id="navbar-mobile" style="">
                    <ul class="nav navbar-nav mr-auto float-left">
                        <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs is-active" href="#"><i class="fas fa-bars"></i></a></li>
                    </ul>
                    <ul class="nav navbar-nav float-right">
                        <li class="dropdown dropdown-notification nav-item">
                            <a class="nav-link nav-link-label" href="#" data-toggle="dropdown" aria-expanded="false"><i class="ficon far fa-bell"></i><span class="badge badge-pill badge-default badge-info badge-default badge-up">5              </span></a>
                            <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                                <li class="dropdown-menu-header">
                                    <h6 class="dropdown-header m-0"><span class="grey darken-2">Messages</span></h6><span class="notification-tag badge badge-default badge-warning float-right m-0">4 New</span>
                                </li>
                                <li class="scrollable-container media-list w-100 ps-container ps-theme-dark ps-active-y" data-ps-id="1c2cfd8d-c0d2-b35e-c31e-9c3f122577b8">
                                    <a href="javascript:void(0)">
                                        <div class="media">
                                            <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="../../../app-assets/images/portrait/small/avatar-s-19.png" alt="avatar"><i></i></span></div>
                                            <div class="media-body">
                                                <h6 class="media-heading">Margaret Govan</h6>
                                                <p class="notification-text font-small-3 text-muted">I like your portfolio, let's start.</p><small>
                                                    <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">Today</time>
                                                </small>
                                            </div>
                                        </div>
                                    </a><a href="javascript:void(0)">
                                        <div class="media">
                                            <div class="media-left"><span class="avatar avatar-sm avatar-busy rounded-circle"><img src="../../../app-assets/images/portrait/small/avatar-s-2.png" alt="avatar"><i></i></span></div>
                                            <div class="media-body">
                                                <h6 class="media-heading">Bret Lezama</h6>
                                                <p class="notification-text font-small-3 text-muted">I have seen your work, there is</p><small>
                                                    <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">Tuesday</time>
                                                </small>
                                            </div>
                                        </div>
                                    </a><a href="javascript:void(0)">
                                        <div class="media">
                                            <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="../../../app-assets/images/portrait/small/avatar-s-3.png" alt="avatar"><i></i></span></div>
                                            <div class="media-body">
                                                <h6 class="media-heading">Carie Berra</h6>
                                                <p class="notification-text font-small-3 text-muted">Can we have call in this week ?</p><small>
                                                    <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">Friday</time>
                                                </small>
                                            </div>
                                        </div>
                                    </a><a href="javascript:void(0)">
                                        <div class="media">
                                            <div class="media-left"><span class="avatar avatar-sm avatar-away rounded-circle"><img src="../../../app-assets/images/portrait/small/avatar-s-6.png" alt="avatar"><i></i></span></div>
                                            <div class="media-body">
                                                <h6 class="media-heading">Eric Alsobrook</h6>
                                                <p class="notification-text font-small-3 text-muted">We have project party this saturday.</p><small>
                                                    <time class="media-meta text-muted" datetime="2015-06-11T18:29:20+08:00">last month</time>
                                                </small>
                                            </div>
                                        </div>
                                    </a><div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; height: 255px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 191px;"></div></div>
                                </li>
                                <li class="dropdown-menu-footer"><a class="dropdown-item text-muted text-center" href="javascript:void(0)">Read all messages</a></li>
                            </ul>
                        </li>
                        <li class="dropdown dropdown-user nav-item">
                            <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown" aria-expanded="false"><span class="avatar avatar-online"><img src="https://pixinvent.com/bootstrap-admin-template/robust/app-assets/images/portrait/small/avatar-s-1.png" alt="avatar"><i></i></span><span class="user-name">John Doe</span></a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="user-profile.html"><i class="ft-user"></i> Edit Profile</a><a class="dropdown-item" href="email-application.html"><i class="ft-mail"></i> My Inbox</a><a class="dropdown-item" href="user-cards.html"><i class="ft-check-square"></i> Task</a><a class="dropdown-item" href="chat-application.html"><i class="ft-message-square"></i> Chats</a>
                                <div class="dropdown-divider"></div><a class="dropdown-item" href="login-with-bg-image.html"><i class="ft-power"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>



    <div class="main-menu menu-fixed menu-dark menu-accordion    menu-shadow " data-scroll-to-active="true">
        <div class="main-menu-content ps-container ps-theme-light" data-ps-id="009a77dc-8cf0-844b-58c2-9cc863fda767" style="height: 1275.03px;">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                <li class="navigation-header">
                    <span data-i18n="nav.category.layouts">Layouts</span><i class="ft-more-horizontal ft-minus" data-toggle="tooltip" data-placement="right" data-original-title="Layouts"></i>
                </li>
                <li class="nav-item has-sub">
                    <a href="@Url.Action("Index","Parametros")"><i class="fas fa-cloud"></i><span class="menu-title" data-i18n="nav.page_layouts.main">Page layouts</span></a>
                </li>
                <li class="nav-item has-sub">
                    <a href="#"><i class="icon-list"></i><span class="menu-title" data-i18n="nav.navbars.main">Navbars</span><span class="badge badge badge-success float-right mr-2">New</span></a>
                    <ul class="menu-content" style="">
                        <li class="">
                            <a class="menu-item" href="navbar-light.html" data-i18n="nav.navbars.nav_light">Navbar Light</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                <li class="navigation-header">
                    <span data-i18n="nav.category.layouts">administrador</span><i class="ft-more-horizontal ft-minus" data-toggle="tooltip" data-placement="right" data-original-title="Layouts"></i>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Parametros")"><i class="fas fa-cogs"></i><span class="menu-title">Parâmetros</span></a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Parametros")"><i class="fas fa-user-friends"></i><span class="menu-title">Usuários</span><span class="badge badge badge-success float-right mr-2">250</span></a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Parametros")"><i class="fas fa-user-friends"></i><span class="menu-title">Equipes</span></a>
                </li>
            </ul>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; height: 1275px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div>
        </div>
    </div>

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="footer footer-static footer-light navbar-border">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span class="float-md-left d-block d-md-inline-block">Copyright  © 2018 <a class="text-bold-800 grey darken-2" href="https://1.envato.market/pixinvent_portfolio" target="_blank">PIXINVENT </a>, All rights reserved. </span><span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Hand-crafted &amp; Made with <i class="ft-heart pink"></i></span></p>
    </footer>

    @Scripts.Render("~/Content/js")

</body>
</html>